---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ola-kustomization
  namespace: flux-system
spec:
  interval: 30s
  path: ./files
  prune: true
  sourceRef:
    kind: GitRepository

    name: git-ola
  targetNamespace: app
